JuliaPOMDP/Registry

R/RockSample/Deps.toml
R/RockSample/Package.toml
R/RockSample/Versions.toml
Registry.toml

UUID: de008ff0-c357-11e8-3329-7fe746fe836e
Repo: https://github.com/MaximeBouton/RockSample.jl.git
Tree: 9f8b008aa1c4047de62bfd75612a79d66fd7db61

New package: RockSample v0.1.0

---

P/POMDPXFiles/Compat.toml
P/POMDPXFiles/Deps.toml
P/POMDPXFiles/Versions.toml

UUID: c6f6ee83-58c6-5336-a19f-2c76817e1af6
Repo: https://github.com/JuliaPOMDP/POMDPXFiles.jl.git
Tree: 926f690f7dd3e8bb9cc54bd0e2e5acbd6c77032c

New version: POMDPXFiles v0.2.0

---

A/ARDESPOT/Compat.toml
A/ARDESPOT/Deps.toml
A/ARDESPOT/Versions.toml

UUID: d96c9ae4-3372-47d5-8a88-316ae77be8cf
Repo: https://github.com/JuliaPOMDP/ARDESPOT.jl
Tree: 3403e982c589a60378dc7c8378d910ad0395b6b6

New version: ARDESPOT v0.3.0

---

M/MCTS/Compat.toml
M/MCTS/Deps.toml
M/MCTS/Versions.toml

UUID: e12ccd36-dcad-5f33-8774-9175229e7b33
Repo: https://github.com/JuliaPOMDP/MCTS.jl.git
Tree: 7b3376240757ca3b52236bf79751469db78b1bb7

New version: MCTS v0.4.0

---

T/TabularTDLearning/Compat.toml
T/TabularTDLearning/Deps.toml
T/TabularTDLearning/Versions.toml

UUID: df77095f-98f0-51e5-a706-d0ff5a5ad33f
Repo: https://github.com/JuliaPOMDP/TabularTDLearning.jl.git
Tree: d7dc5eb9eca26febf4069a1576f14d30e47f7cf5

New version: TabularTDLearning v0.3.0

---

M/MCVI/Compat.toml
M/MCVI/Deps.toml
M/MCVI/Versions.toml

UUID: 30d33687-f7ed-5b0d-8b26-3dc9b7abd572
Repo: https://github.com/JuliaPOMDP/MCVI.jl.git
Tree: 6076c2af337558750cbb1309ab5ec587442381ea

New version: MCVI v0.3.0

---

Q/QMDP/Compat.toml
Q/QMDP/Deps.toml
Q/QMDP/Package.toml
Q/QMDP/Versions.toml

UUID: 3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2
Repo: https://github.com/JuliaPOMDP/QMDP.jl
Tree: 18bb4ab52e312ad30f9890c73fe1fecdc6831db2

New version: QMDP v0.1.3

---

P/POMDPFiles/Compat.toml
P/POMDPFiles/Deps.toml
P/POMDPFiles/Versions.toml

UUID: 9cf5b727-2e06-5671-8c87-8c6b0f729d5d
Repo: http://github.com/JuliaPOMDP/POMDPFiles.jl.git
Tree: 74cd6e096eaee79c7e9e8c32a625d843cb37db68

New version: POMDPFiles v0.2.0

---

P/POMDPSolve/Compat.toml
P/POMDPSolve/Deps.toml
P/POMDPSolve/Versions.toml

UUID: a575d7f4-a5df-53f5-8ba4-9d691c1ba8ff
Repo: https://github.com/JuliaPOMDP/POMDPSolve.jl.git
Tree: 326f35e9a1919f2400273d816a1d3ac687e0c319

New version: POMDPSolve v0.2.0

---

D/DeepQLearning/Versions.toml

Tree: 8fc8df79d58c1aea1317d0d0226c5b91fec55d2e

New version: DeepQLearning v0.3.5

---

M/MCTS/Deps.toml

@rejuvyesh what do you think? will this fix it?

delete Registrator dependency for MCTS

---

C/ContinuumWorld/Compat.toml
C/ContinuumWorld/Deps.toml
C/ContinuumWorld/Versions.toml

UUID: 5cbb95a3-277b-5373-895a-7e14bd91b3cc
Repo: https://github.com/JuliaPOMDP/ContinuumWorld.jl
Tree: 2f42b8f2955f473f10b36aa6e80a74ff45693b98
Registrator tree SHA: unknown

New version: ContinuumWorld v0.3.0

---

D/DeepQLearning/Versions.toml

Tree: ca58cba29084d3356b3bd2798e37a14f82861a34

New version: DeepQLearning v0.4.1

---

D/DeepQLearning/Versions.toml

Tree: 86d48bef6f732cb9b1220e52b5ba6cb1a6023182

New version: DeepQLearning v0.4.5

---

T/TabularTDLearning/Compat.toml
T/TabularTDLearning/Versions.toml

UUID: df77095f-98f0-51e5-a706-d0ff5a5ad33f
Repo: https://github.com/JuliaPOMDP/TabularTDLearning.jl.git
Tree: 11bce6b9e3d6660d14643480ab3300d6d19137d7

New version: TabularTDLearning v0.4.0

---

D/DeepQLearning/Compat.toml
D/DeepQLearning/Versions.toml

Tree: a5c234b7c78682091a48c77098afeccec8d87f76

New version: DeepQLearning v0.5.0

---

D/DiscreteValueIteration/Compat.toml
D/DiscreteValueIteration/Deps.toml
D/DiscreteValueIteration/Versions.toml

UUID: 4b033969-44f6-5439-a48b-c11fa3648068
Repo: https://github.com/JuliaPOMDP/DiscreteValueIteration.jl.git
Tree: 52a4dc28c93f5a06cde91be16f984d093a140534

New version: DiscreteValueIteration v0.4.3

---

R/RLInterface/Compat.toml
R/RLInterface/Versions.toml

UUID: 3065fe53-3878-5aed-aae7-ab641be43734
Repo: https://github.com/JuliaPOMDP/RLInterface.jl
Tree: 49086fe4362c48bab17f31a573b4ee67d8f11736

New version: RLInterface v0.3.7

---

T/TabularTDLearning/Compat.toml
T/TabularTDLearning/Deps.toml
T/TabularTDLearning/Versions.toml

UUID: df77095f-98f0-51e5-a706-d0ff5a5ad33f
Repo: https://github.com/JuliaPOMDP/TabularTDLearning.jl.git
Tree: 0da236f5204e967e4abcc6c6792ef33695c32d6f

New version: TabularTDLearning v0.4.1

---

D/DeepQLearning/Compat.toml
D/DeepQLearning/Deps.toml
D/DeepQLearning/Versions.toml

Tree: 18ac918697d48744a8d3d9d0f0b4da3fd0e7d046

New version: DeepQLearning v0.5.1

---

.travis.yml

@rejuvyesh , thanks for adding the basic tests. Do we need to do it on so many platforms though? Right now it looks like it is just parsing the toml files. Could we just do that on julia 1 and linux?

only test on Julia 1 and linux

---

M/MCTS/Compat.toml
M/MCTS/Deps.toml
M/MCTS/Versions.toml

UUID: e12ccd36-dcad-5f33-8774-9175229e7b33
Repo: https://github.com/JuliaPOMDP/MCTS.jl.git
Tree: 152a2ac36778a0db2db41d0645e37fd744586b90

New version: MCTS v0.4.3

---

Q/QMDP/Compat.toml
Q/QMDP/Deps.toml
Q/QMDP/Versions.toml

UUID: 3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2
Repo: https://github.com/JuliaPOMDP/QMDP.jl.git
Tree: f98a0cc1436db01557e3e68555d53f3428b55287

New version: QMDP v0.1.4

---

F/FIB/Compat.toml
F/FIB/Versions.toml

UUID: 13b007ba-0ca8-5af2-9adf-bc6a6301e25a
Repo: https://github.com/JuliaPOMDP/FIB.jl.git
Tree: 13ddefd9846e90324c3146d648c12fee2c612295

New version: FIB v0.4.1

---

L/LocalApproximationValueIteration/Compat.toml
L/LocalApproximationValueIteration/Deps.toml
L/LocalApproximationValueIteration/Versions.toml

UUID: a40420fb-f401-52da-a663-f502e5b95060
Repo: https://github.com/JuliaPOMDP/LocalApproximationValueIteration.jl
Tree: 32c84469b3e2007e66f1baa03f06289ae83d7359

New version: LocalApproximationValueIteration v0.4.1

---

G/GlobalApproximationValueIteration/Compat.toml
G/GlobalApproximationValueIteration/Deps.toml
G/GlobalApproximationValueIteration/Versions.toml

UUID: 277f244e-4908-11e9-33c2-5d5365097ef8
Repo: https://github.com/JuliaPOMDP/GlobalApproximationValueIteration.jl
Tree: 2ef13205e31bf1ca7c4d385c13f66791123a2dba

New version: GlobalApproximationValueIteration v0.2.1

---

A/AEMS/Compat.toml
A/AEMS/Versions.toml

UUID: 3b430cce-3194-5812-b203-bf9e73c3e836
Repo: https://github.com/JuliaPOMDP/AEMS.jl
Tree: 3efe1c25482b4fca404e807001e3d8c0a6e57b70

New version: AEMS v0.1.3

---

I/IncrementalPruning/Compat.toml
I/IncrementalPruning/Deps.toml
I/IncrementalPruning/Versions.toml

UUID: 82ee451e-1805-57fd-b4f9-e90c19bcb3e9
Repo: https://github.com/JuliaPOMDP/IncrementalPruning.jl.git
Tree: 050dd9818c1f7071bc9806d59bc0042ca55370cf

New version: IncrementalPruning v0.2.4

---

P/POMDPFiles/Compat.toml
P/POMDPFiles/Versions.toml

UUID: 9cf5b727-2e06-5671-8c87-8c6b0f729d5d
Repo: http://github.com/JuliaPOMDP/POMDPFiles.jl.git
Tree: f022f84e692a71da366f075871931291a5485eb7

New version: POMDPFiles v0.2.2

---

P/POMDPSolve/Compat.toml
P/POMDPSolve/Versions.toml

UUID: a575d7f4-a5df-53f5-8ba4-9d691c1ba8ff
Repo: https://github.com/JuliaPOMDP/POMDPSolve.jl.git
Tree: b14d152d66f169283988ec2fde634e6250216e7f

New version: POMDPSolve v0.2.1

---

A/ARDESPOT/Compat.toml
A/ARDESPOT/Versions.toml

UUID: d96c9ae4-3372-47d5-8a88-316ae77be8cf
Repo: https://github.com/JuliaPOMDP/ARDESPOT.jl
Tree: 086370aee5afe66c7fc9e5a9d3024e245e92dde7

New version: ARDESPOT v0.3.3

---

P/POMCPOW/Compat.toml
P/POMCPOW/Versions.toml

UUID: 4c53ee00-974c-466f-8fa5-8dd73959bbab
Repo: https://github.com/JuliaPOMDP/POMCPOW.jl
Tree: b5412fa5d4ac9daf744161a7167c11a7e1bf26de

New version: POMCPOW v0.3.2
